import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

public class Main extends javax.swing.JFrame {

    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
       // dt();
        //time();
    }
    public void dt(){
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("MMM d y"); 
        String dd = sdf.format(d);
        date.setText(" Date: "+ dd);
    }
        Timer t;
        SimpleDateFormat st;   
    public void time(){

        t = new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e){
                //throw new UnsupportedOperationException("Not supported yet");
                Date dt = new Date();
                st = new SimpleDateFormat("hh:mm:ss a");
                String tt = st.format(dt);
                time.setText(" Time: "+tt);  
            }   
        }); 
        t.start();
    }    
    
    
    
    
    public void product(){
        DefaultTableModel tblm = (DefaultTableModel) tblmain.getModel();
        
        tblm.setRowCount(0);
        PreparedStatement ps;
        ResultSet rs;
        String sql = "SELECT * FROM `product`";
        
        try{
            ps = dbConnect.getConnection().prepareStatement(sql);
            rs = ps.executeQuery();
            
            while(rs.next()){
            
                String id = rs.getString("ID");
                String productname = rs.getString("Product_Name");
                String type = rs.getString("Type");
                String quantity = rs.getString("Quantity");
                String price = rs.getString("Price");
                String datereceive = rs.getString("Date_Received");
                String datereleased = rs.getString("Date_Released");
                String eupo = rs.getString("EU_PO");
                String poref = rs.getString("PO_REF");
                String brand = rs.getString("Brand");
                String description = rs.getString("Product_Description");
                String model = rs.getString("Model");
                String supplier = rs.getString("Supplier");
                
                String warranty = rs.getString("Warranty");
                String sales = rs.getString("Sales");
               
                String tbData[]={id,productname,quantity,price,sales};
                tblm.addRow(tbData);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmain = new javax.swing.JTable();
        addorder = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        searchproduct = new javax.swing.JButton();
        editproduct = new javax.swing.JButton();
        addproduct = new javax.swing.JButton();
        deleteproduct = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1022, 627));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblmain.setAutoCreateRowSorter(true);
        tblmain.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblmain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Quantity", "Price", "Sales"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblmain.setAutoscrolls(false);
        tblmain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblmain.setGridColor(new java.awt.Color(0, 0, 0));
        tblmain.setInheritsPopupMenu(true);
        tblmain.setRowHeight(40);
        tblmain.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblmain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblmainMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblmain);
        if (tblmain.getColumnModel().getColumnCount() > 0) {
            tblmain.getColumnModel().getColumn(0).setResizable(false);
            tblmain.getColumnModel().getColumn(1).setResizable(false);
            tblmain.getColumnModel().getColumn(2).setResizable(false);
            tblmain.getColumnModel().getColumn(3).setResizable(false);
            tblmain.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 1200, 260));

        addorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/order.png"))); // NOI18N
        addorder.setText("Add  Order");
        addorder.setBorder(null);
        addorder.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addorderActionPerformed(evt);
            }
        });
        jPanel1.add(addorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 490, 130, 60));

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        logout.setText("Log out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 130, 140, 70));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 70)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VAPAPE INVENTORY MANAGEMENT SYSTEM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 1140, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        jButton1.setText("Update");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 490, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sales.png"))); // NOI18N
        jButton2.setText("Sales");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, 120, 60));

        date.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        date.setText("0");
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 210, 30));

        time.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        time.setText("0");
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 180, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 110, 110));

        searchproduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        searchproduct.setText("Search Product");
        searchproduct.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        searchproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchproductActionPerformed(evt);
            }
        });
        jPanel1.add(searchproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 160, 60));

        editproduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        editproduct.setText("Edit Product");
        editproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editproductActionPerformed(evt);
            }
        });
        jPanel1.add(editproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, 60));

        addproduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        addproduct.setText("Add Product");
        addproduct.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addproductActionPerformed(evt);
            }
        });
        jPanel1.add(addproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 160, 60));

        deleteproduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/del.png"))); // NOI18N
        deleteproduct.setText("Delete Product");
        deleteproduct.setFocusable(false);
        deleteproduct.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        deleteproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteproductActionPerformed(evt);
            }
        });
        jPanel1.add(deleteproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 170, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendar.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 110, 30));

        jLabel4.setText("__________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1320, 80));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wall.jpg"))); // NOI18N
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );

        setSize(new java.awt.Dimension(1305, 656));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addorderActionPerformed
        AddOrder addorder = new AddOrder();
        addorder.AddOrderCombo();
        addorder.show();
    }//GEN-LAST:event_addorderActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        loginsystem login = new loginsystem();
        dispose();
        login.show();
    }//GEN-LAST:event_logoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        product();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        PointOfSale pointofsale = new PointOfSale();
        pointofsale.order();
        pointofsale.total();
        pointofsale.show();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblmainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmainMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblmainMouseClicked

    private void deleteproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteproductActionPerformed
        DeleteProduct deleteproduct = new DeleteProduct();
        deleteproduct.deleteIDCombo();
        deleteproduct.show();
    }//GEN-LAST:event_deleteproductActionPerformed

    private void editproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editproductActionPerformed
        EditProduct editproduct = new EditProduct();
        editproduct.show();
        editproduct.chooseEditCombo();
        editproduct.chooseIDCombo();
    }//GEN-LAST:event_editproductActionPerformed

    private void searchproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchproductActionPerformed
        SearchProduct searchproduct = new SearchProduct();
        searchproduct.show();
        searchproduct.updateSearchCombo();

    }//GEN-LAST:event_searchproductActionPerformed

    private void addproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addproductActionPerformed
        AddProduct addproduct = new AddProduct();
        addproduct.show();
    }//GEN-LAST:event_addproductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addorder;
    private javax.swing.JButton addproduct;
    private javax.swing.JLabel date;
    private javax.swing.JButton deleteproduct;
    private javax.swing.JButton editproduct;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private javax.swing.JButton searchproduct;
    private javax.swing.JTable tblmain;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
